import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'inverse-surface': 'var(--inverse-surface)',
        'inverse-on-surface': 'var(--inverse-on-surface)',

        primary: 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        'primary-container': 'var(--primary-container)',
        'on-primary-container': 'var(--on-primary-container)',
        'primary-fixed': 'var(--primary-fixed)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'inverse-primary': 'var(--inverse-primary)',
        'surface-tint': 'var(--surface-tint)',

        secondary: 'var(--secondary)',
        'on-secondary': 'var(--on-secondary)',
        'secondary-container': 'var(--secondary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',

        tertiary: 'var(--tertiary)',
        'on-tertiary': 'var(--on-tertiary)',
        'tertiary-container': 'var(--tertiary-container)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',

        error: 'var(--error)',
        'on-error': 'var(--on-error)',
        'error-container': 'var(--error-container)',
        'on-error-container': 'var(--on-error-container)',

        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',

        credit: 'var(--credit)',
        debit: 'var(--debit)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
      },
      fontFamily: {
        'headline': ['var(--font-headline)'],
        'body': ['var(--font-body)'],
        'mono': ['var(--font-mono)'],
        
        'headline-md': ['var(--font-headline)'],
        'display-xl': ['var(--font-headline)'],
        'body-lg': ['var(--font-body)'],
        'body-sm': ['var(--font-body)'],
        'headline-lg-mobile': ['var(--font-headline)'],
        'body-md': ['var(--font-body)'],
        'headline-lg': ['var(--font-headline)'],
        'label-caps': ['var(--font-mono)'],
        'headline-sm': ['var(--font-headline)'],
        'display-xl-mobile': ['var(--font-headline)'],
        'label-numeric': ['var(--font-mono)']
      },
      spacing: {
        'space-xs': 'var(--space-xs)',
        'space-sm': 'var(--space-sm)',
        'space-md': 'var(--space-md)',
        'space-lg': 'var(--space-lg)',
        'space-xl': 'var(--space-xl)',
        'gutter': 'var(--gutter)',
        'gutter-desktop': 'var(--gutter)',
        'margin': 'var(--margin)',
        'margin-tablet': 'var(--margin-md)',
        'margin-desktop': 'var(--margin-lg)',
      },
      fontSize: {
        'headline-md': ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        'display-xl': ["5.5rem", { lineHeight: "5.75rem", letterSpacing: "-0.03em", fontWeight: "400" }],
        'body-lg': ["1.125rem", { lineHeight: "1.875rem", letterSpacing: "0em", fontWeight: "400" }],
        'body-sm': ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "500" }],
        'headline-lg-mobile': ["2rem", { lineHeight: "2.375rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        'body-md': ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        'headline-lg': ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.02em", fontWeight: "400" }],
        'label-caps': ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.08em", fontWeight: "700" }],
        'headline-sm': ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        'display-xl-mobile': ["3rem", { lineHeight: "3.25rem", letterSpacing: "-0.02em", fontWeight: "400" }],
        'label-numeric': ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.02em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
} satisfies Config;
