"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useMemo, useState } from "react";

export type WorkflowScreenKind =
  | "customers" | "customer-new" | "customer-detail" | "plans"
  | "accounts" | "account-new" | "account-detail" | "statement"
  | "deposit" | "withdraw" | "transaction-detail" | "fixed-deposits"
  | "fixed-deposit-new" | "interest-runs" | "audit" | "parameters"
  | "admin-users" | "admin-health" | "reconciliation" | "report-agent" | "report-account" | "report-fd"
  | "report-interest" | "report-customer";

interface WorkflowScreenProps { kind: WorkflowScreenKind; }

const customers = [
  ["CUS-000184", "Nadeesha Perera", "Colombo Main", "Assigned to A. Fernando", "Active"],
  ["CUS-000241", "Kamal Jayasinghe", "Kandy", "Assigned to M. Silva", "Active"],
  ["CUS-000309", "S. M. Fathima", "Galle", "Verification pending", "Pending"],
];
const accounts = [
  ["SAV-100284", "Nadeesha Perera", "Women’s Growth", "LKR 42,500.00", "ACTIVE"],
  ["SAV-100301", "Kamal Jayasinghe · 2 holders", "Family Saver", "LKR 18,220.00", "ACTIVE"],
  ["SAV-100344", "S. M. Fathima", "Starter", "LKR 5,000.00", "ACTIVE"],
];
const ledger = [
  ["27 Sep 2026 10:12", "DEP-20260927-00128", "Deposit", "+ LKR 10,000.00", "LKR 42,500.00"],
  ["16 Sep 2026 14:03", "WDL-20260916-00082", "Withdrawal", "− LKR 2,500.00", "LKR 32,500.00"],
  ["30 Aug 2026 09:00", "INT-20260830-00018", "Interest credit", "+ LKR 120.00", "LKR 35,000.00"],
];

function Header({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) {
  return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1 className="page-title">{title}</h1><p className="page-description">{description}</p></div>{action}</div>;
}

function Status({ children }: { children: ReactNode }) { const value = String(children); return <span className={`status-pill status-${value.toLowerCase()}`}>{children}</span>; }
function Money({ children, debit = false }: { children: ReactNode; debit?: boolean }) { return <span className={`amount font-medium ${debit ? "text-[var(--debit)]" : "text-[var(--credit)]"}`}>{children}</span>; }
function Field({ label, required, hint, type = "text", placeholder }: { label: string; required?: boolean; hint?: string; type?: string; placeholder?: string }) {
  const id = label.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-");
  return <label className="field"><span>{label}{required ? " (required)" : ""}</span><input className="input" id={id} name={id} placeholder={placeholder} type={type} required={required} />{hint ? <small>{hint}</small> : null}</label>;
}
function SelectField({ label, required, options }: { label: string; required?: boolean; options: string[] }) {
  const id = label.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-");
  return <label className="field"><span>{label}{required ? " (required)" : ""}</span><select className="input" id={id} name={id} required={required}><option value="">Select {label.toLowerCase()}</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>;
}
function Notice({ children }: { children: ReactNode }) { return <p className="workflow-notice" aria-live="polite">{children}</p>; }
function DataTable({ headers, children }: { headers: string[]; children: ReactNode }) { return <div className="table-wrap"><table className="data-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }

function ActionForm({ type }: { type: "deposit" | "withdraw" }) {
  const [submitted, setSubmitted] = useState(false);
  const verb = type === "deposit" ? "Deposit" : "Withdrawal";
  function submit(event: FormEvent<HTMLFormElement>): void { event.preventDefault(); setSubmitted(true); }
  return <><Header eyebrow="Financial posting" title={`Post a ${verb.toLowerCase()}`} description={`${verb}s are posted to the ledger as an atomic operation. You will review the amount and resulting balance before it is submitted.`} />
    {submitted ? <section className="card confirmation-card"><p className="eyebrow">Confirmation required</p><h2>Review {verb.toLowerCase()} details</h2><dl><div><dt>Account</dt><dd>SAV-100284 · Nadeesha Perera</dd></div><div><dt>Posting amount</dt><dd>{type === "deposit" ? "+" : "−"} LKR 10,000.00</dd></div><div><dt>Projected balance</dt><dd>LKR {type === "deposit" ? "52,500.00" : "32,500.00"}</dd></div></dl><div className="flex flex-wrap gap-3"><button className="btn btn-primary" type="button" onClick={() => setSubmitted(false)}>Back to edit</button><button className="btn btn-secondary" type="button">Confirm when service is connected</button></div><Notice>Frontend prototype only: the eventual request uses a CSRF token and a fresh Idempotency-Key; the server and database make the final decision.</Notice></section> : <form className="card form-grid max-w-3xl" onSubmit={submit}><div className="form-section"><h2>Account and amount</h2><SelectField label="Account" required options={["SAV-100284 · Nadeesha Perera · LKR 42,500.00", "SAV-100301 · Kamal Jayasinghe · LKR 18,220.00"]} /><Field label="Amount (LKR)" required type="text" placeholder="0.00" hint="Enter two decimal places. Money is confirmed by the server as a NUMERIC value." /><SelectField label="Channel" required options={["Cash counter", "Mobile agent", "Bank transfer"]} /></div>{type === "withdraw" ? <div className="form-section"><h2>Authority</h2><SelectField label="On behalf of holder" required options={["Nadeesha Perera — primary holder", "Kamal Jayasinghe — authorised holder"]} /><Notice>Mandate, account status, daily limit and post-withdrawal minimum are verified after the server locks the account.</Notice></div> : null}<div className="form-section"><h2>Reference</h2><Field label="Narration" placeholder="Optional customer-facing note" /><button className="btn btn-primary" type="submit">Review {verb.toLowerCase()}</button></div></form>}</>;
}

function Report({ name, type }: { name: string; type: "agent" | "account" | "fd" | "interest" | "customer" }) {
  const rows = type === "agent" ? [["A. Fernando", "Colombo Main", "24", "LKR 184,200.00"], ["M. Silva", "Kandy", "18", "LKR 132,500.00"]] : type === "fd" ? [["FD-00082", "SAV-100284", "12 month Growth", "LKR 100,000.00", "27 Oct 2026"], ["FD-00091", "SAV-100301", "6 month Flex", "LKR 75,000.00", "12 Oct 2026"]] : [["Colombo Main", "September 2026", "18", "LKR 42,560.00"], ["Kandy", "September 2026", "11", "LKR 28,340.00"]];
  const headers = type === "agent" ? ["Agent", "Branch", "Transactions", "Value"] : type === "fd" ? ["FD ID", "Account", "Product", "Principal", "Next payout"] : type === "account" ? ["Account", "Plan", "Opening balance", "Closing balance"] : type === "customer" ? ["Customer", "Deposits", "Withdrawals", "Net activity"] : ["Branch", "Cycle", "Distributions", "Total interest"];
  return <><Header eyebrow="Management reports" title={name} description="Filter values, generated-at metadata, detail rows and totals will use the same scoped query as the eventual CSV export." action={<button className="btn btn-secondary" type="button">Export CSV</button>} /><section className="card report-filter"><div><Field label="From date" type="date" /><Field label="To date" type="date" /></div><div><SelectField label="Branch" options={["All permitted branches", "Colombo Main", "Kandy"]} /><SelectField label="Status" options={["All statuses", "ACTIVE", "MATURED", "CLOSED"]} /></div><button className="btn btn-primary self-end" type="button">Apply filters</button></section><section className="card mt-6"><div className="report-meta"><span>Filters: All permitted branches · 01 Sep 2026—27 Sep 2026</span><span>Generated 27 Sep 2026 10:30 · requested by current user</span></div><DataTable headers={headers}>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td className={index === row.length - 1 ? "amount" : ""} key={cell}>{cell}</td>)}</tr>)}<tr className="report-total"><td colSpan={headers.length - 1}>Grand total</td><td className="amount">LKR 316,700.00</td></tr></DataTable></section></>;
}

/** Renders frontend-only workflow surfaces aligned to the documented MIMS API contracts. */
export function WorkflowScreen({ kind }: WorkflowScreenProps) {
  const content = useMemo(() => {
    if (kind === "deposit" || kind === "withdraw") return <ActionForm type={kind} />;
    if (kind.startsWith("report-")) { const reportKind = kind as Extract<WorkflowScreenKind, `report-${string}`>; const names: Record<typeof reportKind, string> = { "report-agent": "RPT-01 · Agent-wise transactions", "report-account": "RPT-02 · Account summary", "report-fd": "RPT-03 · Active fixed deposits", "report-interest": "RPT-04 · Interest distribution", "report-customer": "RPT-05 · Customer activity" }; return <Report name={names[reportKind]} type={reportKind.replace("report-", "") as "agent" | "account" | "fd" | "interest" | "customer"} />; }
    if (kind === "customers") return <><Header eyebrow="Customer management" title="Customers" description="Search customers by name, customer number, identity or assigned agent. Results are limited to the signed-in user’s permitted branch scope." action={<Link className="btn btn-primary" href="/customers/new">Register customer</Link>} /><section className="card toolbar"><input className="input" placeholder="Search name, customer number or NIC / passport" /><SelectField label="Branch" options={["All permitted branches", "Colombo Main", "Kandy"]} /><button className="btn btn-secondary" type="button">Search</button></section><section className="card mt-6"><DataTable headers={["Customer", "Name", "Branch", "Assignment", "Status", ""]}>{customers.map((customer) => <tr key={customer[0]}><td className="font-mono text-xs">{customer[0]}</td><td className="font-medium">{customer[1]}</td><td>{customer[2]}</td><td>{customer[3]}</td><td><Status>{customer[4]}</Status></td><td><Link className="text-[var(--primary)] underline" href="/customers/demo">View profile</Link></td></tr>)}</DataTable></section></>;
    if (kind === "customer-new") return <CustomerForm />;
    if (kind === "customer-detail") return <CustomerDetail />;
    if (kind === "plans") return <Plans />;
    if (kind === "accounts") return <><Header eyebrow="Savings accounts" title="Accounts" description="Locate individual and joint savings accounts across the branches available to you." action={<Link className="btn btn-primary" href="/accounts/new">Open account</Link>} /><section className="card toolbar"><input className="input" placeholder="Search account, holder name or customer number" /><SelectField label="Account status" options={["All statuses", "ACTIVE", "CLOSED"]} /><button className="btn btn-secondary" type="button">Search</button></section><section className="card mt-6"><DataTable headers={["Account", "Holder(s)", "Savings plan", "Current balance", "Status", ""]}>{accounts.map((account) => <tr key={account[0]}><td className="font-mono text-xs">{account[0]}</td><td>{account[1]}</td><td>{account[2]}</td><td><Money>{account[3]}</Money></td><td><Status>{account[4]}</Status></td><td><Link className="text-[var(--primary)] underline" href="/accounts/demo">View account</Link></td></tr>)}</DataTable></section></>;
    if (kind === "account-new") return <AccountForm />;
    if (kind === "account-detail") return <AccountDetail />;
    if (kind === "statement") return <Statement />;
    if (kind === "transaction-detail") return <TransactionDetail />;
    if (kind === "fixed-deposits") return <FixedDeposits />;
    if (kind === "fixed-deposit-new") return <FixedDepositForm />;
    if (kind === "interest-runs") return <InterestRuns />;
    if (kind === "audit") return <Audit />;
    if (kind === "parameters") return <Parameters />;
    if (kind === "admin-users") return <AdminUsers />;
    if (kind === "admin-health") return <AdminHealth />;
    return <Reconciliation />;
  }, [kind]);
  return <section>{content}</section>;
}

function CustomerForm() { const [review, setReview] = useState(false); return <><Header eyebrow="Customer management" title="Register a customer" description="Capture identity, contact information, assignment and document metadata. Registration is finally verified and committed as one server transaction." />{review ? <section className="card confirmation-card"><p className="eyebrow">Ready for review</p><h2>Customer registration summary</h2><dl><div><dt>Full name</dt><dd>Nadeesha Perera</dd></div><div><dt>Assigned branch</dt><dd>Colombo Main</dd></div><div><dt>Assigned agent</dt><dd>A. Fernando</dd></div><div><dt>Documents</dt><dd>NIC copy · Address proof</dd></div></dl><div className="flex gap-3"><button className="btn btn-secondary" onClick={() => setReview(false)} type="button">Edit details</button><button className="btn btn-primary" type="button">Submit when API is connected</button></div></section> : <form className="card form-grid max-w-3xl" onSubmit={(event) => { event.preventDefault(); setReview(true); }}><div className="form-section"><h2>Identity</h2><Field label="Full name" required /><Field label="NIC or passport number" required hint="This is checked for uniqueness by the database." /><div className="two-col"><Field label="Date of birth" required type="date" /><SelectField label="Gender" options={["Female", "Male", "Other", "Prefer not to say"]} /></div></div><div className="form-section"><h2>Contact details</h2><Field label="Phone number" required type="tel" /><Field label="Email address" type="email" /><Field label="Residential address" required /></div><div className="form-section"><h2>Assignment and documents</h2><div className="two-col"><SelectField label="Branch" required options={["Colombo Main", "Kandy", "Galle"]} /><SelectField label="Assigned agent" required options={["A. Fernando", "M. Silva"]} /></div><Field label="Document references" required placeholder="e.g. NIC-FRONT, ADDRESS-PROOF" hint="The backend accepts document records; actual file handling is added with the document service." /><button className="btn btn-primary" type="submit">Review registration</button></div></form>}</>; }
function CustomerDetail() { return <><Header eyebrow="Customer profile" title="Nadeesha Perera" description="CUS-000184 · Colombo Main · registered 14 Jan 2026" action={<Link className="btn btn-secondary" href="/customers">Back to customers</Link>} /><div className="detail-grid mt-6"><section className="card"><h2>Profile</h2><dl><div><dt>Identity</dt><dd>NIC •••• 4381</dd></div><div><dt>Assigned agent</dt><dd>A. Fernando</dd></div><div><dt>Contact</dt><dd>+94 77 ••• 8391</dd></div><div><dt>Verification</dt><dd><Status>Active</Status></dd></div></dl></section><section className="card"><h2>Linked accounts</h2><Link className="detail-link" href="/accounts/demo">SAV-100284 <span>Women’s Growth · LKR 42,500.00</span></Link><Link className="detail-link" href="/fixed-deposits">FD-00082 <span>12 month Growth · ACTIVE</span></Link></section><section className="card"><h2>Documents</h2><p className="muted">NIC copy · verified 14 Jan 2026</p><p className="muted">Address proof · verified 14 Jan 2026</p></section></div></>; }
function Plans() { return <><Header eyebrow="Product catalogue" title="Savings plans" description="Plan terms are informative here. Eligibility and minimum balances are confirmed by the account-opening routine." /><section className="card mt-6"><DataTable headers={["Plan", "Eligible age", "Minimum balance", "Status", "Effective from"]}><tr><td className="font-medium">Women’s Growth</td><td>18–65</td><td><Money>LKR 1,000.00</Money></td><td><Status>Active</Status></td><td>01 Jan 2026</td></tr><tr><td className="font-medium">Family Saver</td><td>18+</td><td><Money>LKR 2,500.00</Money></td><td><Status>Active</Status></td><td>01 Jan 2026</td></tr></DataTable></section></>; }
function AccountForm() { const [review, setReview] = useState(false); return <><Header eyebrow="Savings accounts" title="Open savings account" description="Use one holder for an individual account, or two to four adult holders plus a joint mandate. The server validates every selected holder and plan." />{review ? <section className="card confirmation-card"><p className="eyebrow">Confirmation required</p><h2>Review account opening</h2><dl><div><dt>Plan</dt><dd>Women’s Growth</dd></div><div><dt>Holders</dt><dd>Nadeesha Perera</dd></div><div><dt>Initial deposit</dt><dd>LKR 5,000.00</dd></div><div><dt>Projected account</dt><dd>New individual savings account</dd></div></dl><button className="btn btn-primary" onClick={() => setReview(false)} type="button">Edit application</button></section> : <form className="card form-grid max-w-3xl" onSubmit={(event) => { event.preventDefault(); setReview(true); }}><div className="form-section"><h2>Account setup</h2><SelectField label="Savings plan" required options={["Women’s Growth · min LKR 1,000.00", "Family Saver · min LKR 2,500.00"]} /><SelectField label="Branch" required options={["Colombo Main", "Kandy"]} /><SelectField label="Account type" required options={["Individual", "Joint"]} /></div><div className="form-section"><h2>Holders and authority</h2><SelectField label="Primary holder" required options={["Nadeesha Perera · CUS-000184", "Kamal Jayasinghe · CUS-000241"]} /><Field label="Additional holder customer numbers" placeholder="For joint accounts, 1–3 additional holders" /><SelectField label="Joint mandate" options={["Any one holder", "All holders", "Specified number of holders"]} /><Field label="Required signatories" type="number" hint="Required for a specified-number mandate." /></div><div className="form-section"><h2>Initial funding</h2><Field label="Initial deposit (LKR)" placeholder="0.00" hint="Optional, but must satisfy the selected plan’s minimum where required." /><button className="btn btn-primary" type="submit">Review account opening</button></div></form>}</>; }
function AccountDetail() { return <><Header eyebrow="Savings account" title="SAV-100284" description="Women’s Growth · Colombo Main · opened 14 Jan 2026" action={<Link className="btn btn-primary" href="/accounts/demo/statement">View statement</Link>} /><div className="detail-grid mt-6"><section className="card balance-card"><p>Available balance</p><strong>LKR 42,500.00</strong><Status>Active</Status><div className="mt-5 flex gap-3"><Link className="btn btn-primary" href="/transactions/deposit">Deposit</Link><Link className="btn btn-secondary" href="/transactions/withdraw">Withdraw</Link></div></section><section className="card"><h2>Holders and mandate</h2><dl><div><dt>Primary holder</dt><dd>Nadeesha Perera</dd></div><div><dt>Authority</dt><dd>Individual account — holder may transact</dd></div><div><dt>Minimum balance</dt><dd>LKR 1,000.00</dd></div></dl></section><section className="card"><h2>Fixed deposit</h2><p className="muted">FD-00082 · Growth 12 months</p><p className="font-medium">Principal: LKR 100,000.00</p><p className="muted">Next interest: 27 Oct 2026</p><Link className="text-[var(--primary)] underline" href="/fixed-deposits">View fixed deposits</Link></section></div></>; }
function Statement() { return <><Header eyebrow="Statement" title="SAV-100284" description="Nadeesha Perera · Current balance LKR 42,500.00" action={<button className="btn btn-secondary" type="button">Download statement</button>} /><section className="card toolbar"><Field label="From date" type="date" /><Field label="To date" type="date" /><button className="btn btn-secondary self-end" type="button">Apply date range</button></section><section className="card mt-6"><DataTable headers={["Posted at", "Reference", "Type", "Amount", "Balance after"]}>{ledger.map((row) => <tr key={row[1]}><td>{row[0]}</td><td className="font-mono text-xs"><Link className="text-[var(--primary)] underline" href="/transactions/demo">{row[1]}</Link></td><td>{row[2]}</td><td><Money debit={String(row[3]).startsWith("−")}>{row[3]}</Money></td><td className="amount">{row[4]}</td></tr>)}</DataTable></section></>; }
function TransactionDetail() { return <><Header eyebrow="Ledger transaction" title="DEP-20260927-00128" description="Immutable posted entry · 27 Sep 2026 10:12 · Colombo Main" /><div className="detail-grid mt-6"><section className="card"><h2>Posting details</h2><dl><div><dt>Account</dt><dd>SAV-100284</dd></div><div><dt>Type</dt><dd>Deposit</dd></div><div><dt>Amount</dt><dd><Money>+ LKR 10,000.00</Money></dd></div><div><dt>Balance after</dt><dd>LKR 42,500.00</dd></div><div><dt>Channel</dt><dd>Cash counter</dd></div></dl></section><section className="card"><h2>Reversal</h2><p className="muted">A reversal creates a compensating ledger entry; the original entry is never edited or deleted.</p><Field label="Reversal reason" required placeholder="Required manager reason" /><button className="btn btn-secondary mt-4" type="button">Request manager reversal</button></section></div></>; }
function FixedDeposits() { return <><Header eyebrow="Fixed deposits" title="Fixed deposits" description="Review active, matured and closed fixed deposits. Fixed-deposit eligibility is recalculated by the server under account lock." action={<Link className="btn btn-primary" href="/fixed-deposits/new">Open fixed deposit</Link>} /><section className="card mt-6"><DataTable headers={["FD ID", "Account", "Product", "Principal", "Rate at opening", "Maturity", "Status"]}><tr><td className="font-mono text-xs">FD-00082</td><td>SAV-100284</td><td>12 month Growth</td><td><Money>LKR 100,000.00</Money></td><td>12.50%</td><td>14 Jan 2027</td><td><Status>Active</Status></td></tr><tr><td className="font-mono text-xs">FD-00091</td><td>SAV-100301</td><td>6 month Flex</td><td><Money>LKR 75,000.00</Money></td><td>10.00%</td><td>12 Dec 2026</td><td><Status>Active</Status></td></tr></DataTable></section></>; }
function FixedDepositForm() { return <><Header eyebrow="Fixed deposits" title="Open a fixed deposit" description="The principal is debited from the selected savings account in the same transaction that opens the deposit." /><form className="card form-grid max-w-2xl" onSubmit={(event) => event.preventDefault()}><div className="form-section"><h2>Funding account</h2><SelectField label="Savings account" required options={["SAV-100284 · LKR 42,500.00 available", "SAV-100301 · LKR 18,220.00 available"]} /><SelectField label="FD product" required options={["6 month Flex · 10.00%", "12 month Growth · 12.50%"]} /><Field label="Principal amount (LKR)" required placeholder="0.00" hint="The account must remain eligible and have sufficient balance at posting time." /></div><section className="form-section"><h2>Expected terms</h2><dl><div><dt>Interest rate</dt><dd>Snapshot at opening</dd></div><div><dt>Maturity date</dt><dd>Calculated from product tenure</dd></div><div><dt>Next interest date</dt><dd>Calculated by the interest cycle</dd></div></dl><button className="btn btn-primary" type="submit">Review fixed deposit</button></section></form></>; }
function InterestRuns() { return <><Header eyebrow="Interest operations" title="Interest runs" description="The 30-day cycle processes each due fixed deposit independently and records exceptions without rolling back successful payouts." action={<button className="btn btn-primary" type="button">Start interest run</button>} /><section className="card toolbar"><Field label="Cycle date" type="date" /><label className="check-field"><input type="checkbox" /> Dry run — show eligible FDs without posting credits</label><button className="btn btn-secondary self-end" type="button">Review run</button></section><section className="card mt-6"><DataTable headers={["Cycle date", "Status", "FDs processed", "Total interest", "Exceptions", "Initiated by"]}><tr><td>30 Aug 2026</td><td><Status>Completed</Status></td><td className="amount">21</td><td><Money>LKR 42,560.00</Money></td><td className="amount">0</td><td>system worker</td></tr><tr><td>30 Jul 2026</td><td><Status>Completed</Status></td><td className="amount">19</td><td><Money>LKR 38,140.00</Money></td><td className="amount">1</td><td>central.ops</td></tr></DataTable></section></>; }
function Audit() { return <><Header eyebrow="Audit and controls" title="Audit log" description="Search immutable audit events by actor, entity, action and time range." /><section className="card report-filter"><div><SelectField label="Actor" options={["All actors", "A. Fernando", "system worker"]} /><SelectField label="Entity type" options={["All entities", "customer", "account", "transaction", "report"]} /></div><div><SelectField label="Action" options={["All actions", "CUSTOMER_CREATED", "DEPOSIT_POSTED", "REPORT_ACCESSED"]} /><Field label="From date" type="date" /></div><button className="btn btn-primary self-end" type="button">Search audit log</button></section><section className="card mt-6"><DataTable headers={["Logged at", "Actor", "Entity", "Action", "Change data"]}><tr><td>27 Sep 2026 10:12</td><td>A. Fernando</td><td>transaction · DEP-…128</td><td>DEPOSIT_POSTED</td><td><button className="text-[var(--primary)] underline" type="button">View JSON</button></td></tr><tr><td>27 Sep 2026 09:47</td><td>admin</td><td>report · RPT-03</td><td>REPORT_ACCESSED</td><td><button className="text-[var(--primary)] underline" type="button">View filters</button></td></tr></DataTable></section></>; }
function Parameters() { return <><Header eyebrow="System administration" title="Parameters and calendar" description="Configuration remains data-driven. Changes are server-authorized, audited and take effect according to the configured business rules." /><div className="detail-grid mt-6"><section className="card"><h2>Operating parameters</h2><DataTable headers={["Key", "Value", "Description", ""]}><tr><td className="font-mono text-xs">withdrawal_daily_limit</td><td>LKR 50,000.00</td><td>Per-account daily limit</td><td><button className="text-[var(--primary)] underline" type="button">Edit</button></td></tr><tr><td className="font-mono text-xs">interest_cycle_days</td><td>30</td><td>FD interest cycle interval</td><td><button className="text-[var(--primary)] underline" type="button">Edit</button></td></tr></DataTable></section><section className="card"><h2>Business calendar</h2><p className="muted">27 Sep 2026 · Business day · 08:30—16:30</p><p className="muted">28 Sep 2026 · Non-business day · Poya Day</p><button className="btn btn-secondary mt-4" type="button">Manage calendar dates</button></section></div></>; }
function AdminUsers() { return <><Header eyebrow="System administration" title="Users and roles" description="Manage staff identities and review their assigned roles. The server controls authorization and never exposes password hashes." action={<button className="btn btn-primary" type="button">Create staff user</button>} /><section className="card toolbar"><input className="input" placeholder="Search username or staff name" /><SelectField label="Role" options={["All roles", "ADMIN", "CENTRAL_OPS", "BRANCH_MANAGER", "AGENT", "AUDITOR"]} /><button className="btn btn-secondary" type="button">Search</button></section><section className="card mt-6"><DataTable headers={["Username", "Role", "Branch scope", "Status", "Last sign-in", ""]}><tr><td className="font-medium">a.fernando</td><td>AGENT</td><td>Colombo Main</td><td><Status>Active</Status></td><td>27 Sep 2026 10:12</td><td><button className="text-[var(--primary)] underline" type="button">Manage</button></td></tr><tr><td className="font-medium">central.ops</td><td>CENTRAL_OPS</td><td>Bank-wide</td><td><Status>Active</Status></td><td>27 Sep 2026 09:15</td><td><button className="text-[var(--primary)] underline" type="button">Manage</button></td></tr></DataTable></section></>; }
function AdminHealth() { return <><Header eyebrow="System administration" title="Application health" description="Operational status, migration state and connection checks are read-only diagnostics for administrators." action={<button className="btn btn-secondary" type="button">Refresh status</button>} /><div className="metric-grid mt-6"><section className="card metric-card"><span>Application</span><strong className="text-[var(--credit)]">Healthy</strong><small>Route handlers responding</small></section><section className="card metric-card"><span>Database connection</span><strong className="text-[var(--credit)]">Available</strong><small>Pool diagnostic (server supplied)</small></section><section className="card metric-card"><span>Schema migrations</span><strong>Current</strong><small>Latest recorded migration</small></section></div><Notice>This screen will populate from the protected health endpoint. It does not expose credentials, raw SQL errors, or internal stack traces.</Notice></>; }
function Reconciliation() { return <><Header eyebrow="Financial controls" title="Reconciliation" description="Compare the denormalised account balance against the immutable ledger and verify each transaction’s recorded running balance." action={<button className="btn btn-secondary" type="button">Export exceptions</button>} /><div className="metric-grid mt-6"><section className="card metric-card"><span>Accounts checked</span><strong>128</strong><small>current balance vs ledger sum</small></section><section className="card metric-card"><span>Ledger variance</span><strong className="text-[var(--credit)]">LKR 0.00</strong><small>all balances reconcile</small></section><section className="card metric-card"><span>Running-balance exceptions</span><strong>0</strong><small>balance_after sequence check</small></section></div><section className="card mt-6"><DataTable headers={["Control", "Scope", "Result", "Checked at"]}><tr><td>D-1 · Current balance vs ledger</td><td>All permitted accounts</td><td><Status>Passed</Status></td><td>27 Sep 2026 10:30</td></tr><tr><td>D-2 · Ledger running balance</td><td>All permitted transactions</td><td><Status>Passed</Status></td><td>27 Sep 2026 10:30</td></tr></DataTable></section></>; }
