 'use client';
import {useEffect,useState} from 'react';
type Row={log_id:string;logged_at:string;actor_type:string;user_id:string|null;entity_type:string;entity_id:string|null;action:string;old_values:Record<string,unknown>|null;new_values:Record<string,unknown>|null};
const empty={actorId:'',entityType:'',entityId:'',action:'',from:'',to:''};
export function AuditScreen(){
 const [filters,setFilters]=useState(empty),[applied,setApplied]=useState(empty),[page,setPage]=useState(1),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');const params=new URLSearchParams({page:String(page),pageSize:'20'});
 Object.entries(applied).forEach(([k,v])=>{if(v)params.set(k,(k==='from'||k==='to')?v+':00+05:30':v);});
 fetch('/api/audit?'+params,{signal:c.signal,cache:'no-store'}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error?.message??'Unable to load audit history.');if(!c.signal.aborted)setRows(data.data);}).catch(e=>{if(!c.signal.aborted){setRows([]);setError(e instanceof Error?e.message:'Unable to load audit history.');}}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[applied,page,attempt]);
 return <div className="space-y-6"><div className="page-header"><div><p className="eyebrow">Control and traceability</p><h1 className="page-title">Audit trail</h1><p className="page-description">Filter activity by actor, entity and action. Times use Asia/Colombo.</p></div></div>
 <form className="card grid gap-4 md:grid-cols-3" onSubmit={e=>{e.preventDefault();setApplied({...filters});setPage(1);}}>{Object.entries(filters).map(([k,v])=><label className="field" key={k}>{({actorId:'Actor UUID',entityType:'Entity type',entityId:'Entity UUID',action:'Action',from:'From (Colombo)',to:'To (Colombo)'} as Record<string,string>)[k]}<input className="input" type={k==='from'||k==='to'?'datetime-local':'text'} value={v} onChange={e=>setFilters({...filters,[k]:e.target.value})}/></label>)}<button className="btn btn-primary" disabled={busy}>Search audit trail</button></form>
 {busy?<p className="card" role="status">Loading audit history…</p>:error?<p className="card" role="alert">{error} <button className="btn btn-secondary" onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>:<section className="card overflow-x-auto"><table className="data-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Changes</th></tr></thead><tbody>{rows.map(r=><tr key={r.log_id}><td>{new Date(r.logged_at).toLocaleString('en-GB',{timeZone:'Asia/Colombo'})}</td><td>{r.actor_type}<br/>{r.user_id}</td><td>{r.action}</td><td>{r.entity_type}<br/>{r.entity_id}</td><td><details><summary>View changes</summary><pre className="whitespace-pre-wrap break-all">{JSON.stringify({before:r.old_values,after:r.new_values},null,2)}</pre></details></td></tr>)}{!rows.length&&<tr><td colSpan={5}>No matching audit entries.</td></tr>}</tbody></table></section>}
 <div className="flex gap-4"><button className="btn btn-secondary" disabled={busy||page===1} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page}</span><button className="btn btn-secondary" disabled={busy||!!error||rows.length<20} onClick={()=>setPage(n=>n+1)}>Next</button></div></div>;
}
